### ISSUE TITLE
Missing URL

### ISSUE THREAD

**Issue by keighrim** [lapps/org.lappsgrid.discriminator#2]
"http://vocab.lappsgrid.org/PhraseStructure" is missing from [Discriminators](https://github.com/lapps/org.lappsgrid.discriminator/blob/master/src/main/java/org/lappsgrid/discriminator/Discriminators.java)

**Comment by keighrim** [comment]
Also, http://vocab.lappsgrid.org/Constituent

**Comment by keighrim** [comment]
Also, http://vocab.lappsgrid.org/Markable

**Comment by keighrim** [comment]
@chunqishi found http://vocab.lappsgrid.org/DependencyStructure is missing too. Putting it here just for the record.

**Comment by ksuderman** [comment]
The new discriminators are now available in the 2.1.0-SNAPSHOT version for testing.

**Comment by keighrim** [comment]
https://github.com/lapps/org.lappsgrid.discriminator/blob/develop/src/main/java/org/lappsgrid/discriminator/Discriminators.java#L162

Typo found:  `DENDENCY_STRUCTURE`.

**Comment by ksuderman** [comment]
Opened oanc/org.lappsgrid.discriminator.dsl#4 to track the typo problem.  The rest of the missing URL have been added so I am closing this issue.
